dump_dir: ./image_token_experiment
name: "image_token_training"
steps: 10000

seed: 42

logging:
    freq: 10
    acc_freq: 1
    wandb:
        project: "lingua-image-tokens"
        name: "image-token-training"
        entity: null

optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0
grad_acc_steps: 4

distributed:
    fsdp_type: full_shard
    compile: true
    selective_activation_checkpointing: true

model:
    dim: 1024
    n_layers: 8
    n_heads: 8
    vocab_size: 32768  # VQGAN codebook size

data:
    root_dir: data
    sources:
        image_tokens: 100.0
    batch_size: 1
    seq_len: 16384  # allows for 4 images of 4096 tokens each
    load_async: true
    n_views: 2  # Need 2 views: one for input, one for target
    add_bos: false  # no need for BOS token for image tokens
    add_eos: false  # no need for EOS token for image tokens
    tokenizer:
        name: "image"
        vocab_size: 32768  # VQGAN codebook size